### ISSUE TITLE
Add Dev Setup instructions

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/auth-service#19]
Add dev setup to ease up dev env

### Tasks
- [ ] Add docker images
- [ ] Add seed data
- [ ] Add instructions to README
