### ISSUE TITLE
Add CI/CD config

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/auth-service#4]
### Tasks
- [ ] Add either gitlab/travis/semaphore/circleci deployments
- [ ] Create staging and prod deployment
- [ ] Add manual trigger for prod deployment
- [ ] Add k8s as part of it
- [ ] Use maesh for circuit breaker and monitoring

**Comment by HandOfGod94** [comment]
Need a new machine before trying out `helm` and `k8s`.
