### ISSUE TITLE
Generate Heroku CI/CD Deployment

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/auth-service#6]
### Tasks
- [x] Use buddy ci 
- [x] Create a heroku app deployment for golang
- [x] Create a staging/review app integrated with github
- [ ] ~Use private paid dynos for the project~ (N/A)

### Questions
- How to manage env configs?

**Comment by HandOfGod94** [comment]
Created a separate card #8 for using configs in heroku deployment
