### ISSUE TITLE
Add ELK Stack Support

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/auth-service#9]
Add log aggregation using Elastic Search, Kibana and Logstash.

### Tasks
- [ ] Add logrus support
- [ ] pump logs via logstash
- [ ] Create kibana dashboards to retrieve the data
